---
os: linux
dist: bionic

jobs:
  include:
    - language: go
      go: 1.13.x
      before_install: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION"
      script:
        - golangci-lint run
        - make test

    - language: go
      go: 1.14.x
      before_install: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION"
      script:
        - golangci-lint run
        - make test

env:
  global:
    # - GO111MODULE: "on"
    - GOLANGCI_LINT_VERSION: "v1.23.8"
